version: '3.8'

services:
  auth-service:
    build: ./service-auth
    container_name: service_auth
    ports:
      - "8001:8000"
    networks:
      - backend
    environment:
      - SERVICE_NAME=service-auth
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/fastapidb

  events-service:
    build: ./service-events
    container_name: service_events
    ports:
      - "8002:8000"
    networks:
      - backend
    environment:
      - SERVICE_NAME=service-events
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/fastapidb

  notifications-service:
    build: ./service-notifications
    container_name: service_notifications
    ports:
      - "8003:8000"
    networks:
      - backend
    environment:
      - SERVICE_NAME=service-notifications
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/fastapidb

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapidb
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
